params [_this];
current_vehicule = _this;

current_vehicule addItemCargo ["ACE_splint",15];
current_vehicule addItemCargo ["ACE_epinephrine",50];
current_vehicule addItemCargo ["ACE_adenosine",30];
current_vehicule addItemCargo ["ACE_morphine",50];
current_vehicule addItemCargo ["ACE_packingBandage",50];
current_vehicule addItemCargo ["ACE_elasticBandage",50];
current_vehicule addItemCargo ["ACE_EarPlugs",10];
current_vehicule addItemCargo ["ACE_quikclot",50];
current_vehicule addItemCargo ["ACE_fieldDressing",50];
current_vehicule addItemCargo ["ACE_bloodIV",10];
current_vehicule addItemCargo ["ACE_bloodIV_250",20];
current_vehicule addItemCargo ["ACE_bloodIV_500",20];
current_vehicule addItemCargo ["ACE_plasmaIV",10];
current_vehicule addItemCargo ["ACE_plasmaIV_250",20];
current_vehicule addItemCargo ["ACE_plasmaIV_500",20];
current_vehicule addItemCargo ["ACE_salineIV",10];
current_vehicule addItemCargo ["ACE_salineIV_250",20];
current_vehicule addItemCargo ["ACE_salineIV_500",20];
current_vehicule addItemCargo ["ACE_surgicalKit",10];
current_vehicule addItemCargo ["ACE_personalAidKit",10];
current_vehicule addItemCargo ["ACE_bodyBag",10];